@startuml

abstract class Pessoa {
    - id: Long
    - nomeCompleto: String
    - dataNascimento: Date
    - CPF: String
    - RG: String
    - genero: String
    - email: String
    - telefoneCelular: String
    - telefoneFixo: String
    - endereco: String
    - estrangeiro: Boolean
    - dadoAcademico: DadoAcademico
    - dadoProfissional: DadoProfissional
}

class DadoAcademico {
    - nivelSerieEscolaridade: NivelSerieEscolaridade
    - escolaridade: Escolaridade
    - orgaoInstituicaoEmpresa: OrgaoInstituicaoEmpresa
}

class DadoProfissional {
    - nivelSerieEscolaridade: NivelSerieEscolaridade
    - Escolaridade: Escolaridade
    - OrgaoInstituicaoEmpresa: OrgaoInstituicaoEmpresa
}



@enduml