@startuml

class Pessoa {
    - id: Long
    - nomeCompleto: String
    - dataNascimento: Date
    - genero: String
    - estrangeiro: Boolean

    - CPF: String
    - RG: String
    - outrosDocumentos: String

    - email: String
    - telefoneCelular: String
    - telefoneFixo: String

    - endereco: Endereco

    - escolaridade: Escolaridade
    - profissaoCargoFuncao: ProfissaoCargoFuncao
    - orgaoInstituicaoEmpresa: OrgaoInstituicaoEmpresa
}

class Endereco {
    - id: Long
    - CEP: String
    - TipoLogradouro: TipoLogradouro
    - nomeLogradouro: String
    - numero: Integer
    - complemento: String
    - bairro: String
    - cidade: String
    - estado: String
    - pais: String
}

class TipoLogradouro {
    - id: Long
    - nomeTipoLogradouro: String
}

class Escolaridade {
    - id: Long
    - nomeDescricao: String
}

class NivelSerieEscolaridade {
    - id: Long
    - nomeDescricao: String
}

class OrgaoInstituicaoEmpresa {
    - id: Long
    - nomeDescricao: String
}

class ProfissaoCargoFuncao {
    - id: Long
    - nomeDescricao: String
}

class RegistroFrequencia {
    - id: Long
    - dataHoraRegistro: LocalDateTime
    - numeroAula: Integer
    - presenca: char
    - conteudoPlanejado: String
    - conteudoMinistrado: String
    - observacoesAnotacoes: String
    - duracaoAula: String
    - fala: Integer
    - audicao: Integer
    - leitura: Integer
    - escrita: Integer
    - tarefa: Integer
    - situacaoTarefa: String
    - app: String
    - engajamento: Integer
    - sala: Integer
}


Pessoa "*" -- "1" Endereco
Pessoa "*" -- "1" Escolaridade
Pessoa "*" -- "1" NivelSerieEscolaridade
Pessoa "*" -- "1" ProfissaoCargoFuncao
Pessoa "*" -- "1" OrgaoInstituicaoEmpresa

Endereco *-- TipoLogradouro

@enduml