@startuml

enum NivelSerieEscolaridade {
    PRIMEIRO_ANO
    SEGUNDO_ANO
    TERCEIRO_ANO
    QUARTO_ANO
    QUINTO_ANO
    SEXTO_ANO
    SETIMO_ANO
    OITAVO_ANO
    NONO_ANO
    PRIMEIRO_ANO_MEDIO
    SEGUNDO_ANO_MEDIO
    TERCEIRO_ANO_MEDIO
}

enum Escolaridade {
    NAO_ALFABETIZADO
    ANALFABETO
    PRE_ESCOLAR
    FUNDAMENTAL_INCOMPLETO
    FUNDAMENTAL_COMPLETO
    MEDIO_INCOMPLETO
    MEDIO_COMPLETO
    SUPERIOR_INCOMPLETO
    SUPERIOR_COMPLETO
    POS_GRADUACAO_INCOMPLETO
    POS_GRADUACAO_COMPLETO
    MESTRADO_INCOMPLETO
    MESTRADO_COMPLETO
    DOUTORADO_INCOMPLETO
    DOUTORADO_COMPLETO
}

enum OrgaoInstituicaoEmpresa {
    WINNER_SCHOOL
    COLEGIO_NAVIRAI
    WIZARD_NAVIRAI
    SENAI
    SESI
    IFMS
    UEMS
    UFMS
    PREFEITURA_MUNICIPAL
    FORUM
    COPASUL
    SICREDI
    SICOOB
    BANCO_DO_BRASIL
    CAIXA_ECONOMICA_FEDERAL
}

enum ProfissaoFuncaoCargo {
    PROFESSOR_EDUCACAO_INFANTIL
    PROFESSOR_ENSINO_FUNDAMENTAL
    PROFESSOR_ENSINO_MEDIO
    PROFESSOR_ENSINO_SUPERIOR
    PROFESSOR_IDIOMAS
    ADVOGADO_A
    JUIZ_A
    PROMOTOR_A
    EMPRESARIO_A
}

enum TipoVia {
    RUA
    AVENIDA
    TRAVESSA
    RODOVIA
    ESTRADA
    ALAMEDA
    BECO
    LARGO
}

enum Complemento {
    APARTAMENTO
    CASA
    SALA
    BLOCO
    LOTE
    QUADRA
    KM
    ANDAR
    TORRE
    GALPAO
    SITIO
    FAZENDA
    CHACARA
    RANCHO
    CONDOMINIO
    VILA
}

@enduml