- name: Github to Drive
  # You may pin to the exact commit or the version.
  # uses: guillep2k/github-to-drive@549e3c7c11b432a04785c73a945eec38dc54d879
on: [push]
  branches:
    - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: guillep2k/github-to-drive@v1.0.0
      with:
        fetch-depth: 0
        lfs: true
    - name: Update Guides
      uses: guillep2k/gitub-to-drive@latest
      env:
        GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
        GDRIVE_FOLDERID: ${{ secrets.GDRIVE_FOLDERID }}
        GIT_ORIGIN: ${{ secrets.GIT_ORIGIN }}
        GIT_SUBDIR: ${{ secrets.GIT_SUBDIR }}
        GIT_GLOB: ${{ secrets.GIT_GLOB }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNELS: ${{ secrets.SLACK_CHANNELS }}
